<%@ Page Title="" Language="C#" MasterPageFile="~/HomeMasterPage.master" AutoEventWireup="true" CodeFile="AddProduct.aspx.cs" Inherits="AddProduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br/>
<br/>
<br/>
<br/>
    <asp:GridView ID="GridView1" runat="server" Width="289px" 
        
    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True" 
    DataSourceID="SqlDataSource1" BackColor="#DEBA84" BorderColor="#DEBA84" 
    BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
        <Columns>
            <asp:BoundField DataField="VendorName" HeaderText="VendorName" 
                SortExpression="VendorName" />
            <asp:BoundField DataField="ProductName" HeaderText="ProductName"
                SortExpression="ProductName" />
            <asp:BoundField DataField="Category" HeaderText="Category" 
                SortExpression="Category" />
            <asp:BoundField DataField="Price" HeaderText="Price" 
                SortExpression="Price" />
            <asp:TemplateField>
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Image ID="Image1" runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
        <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
        <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FFF1D4" />
        <SortedAscendingHeaderStyle BackColor="#B95C30" />
        <SortedDescendingCellStyle BackColor="#F1E5CE" />
        <SortedDescendingHeaderStyle BackColor="#93451F" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
    SelectCommand="SELECT * FROM [Vendor]" 
        InsertCommand="INSERT INTO [Vendor] ([VendorName], [ProductName], [Category], [Price]) VALUES (@VendorName, @ProductName, @Category, @Price)">
        <InsertParameters>
            <asp:Parameter Name="VendorName" Type="String" />
            <asp:Parameter Name="ProductName" Type="String" />
            <asp:Parameter Name="Category" Type="String" />
            <asp:Parameter Name="Price" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
    <br/>
   <br/>
 <br/>
    <br/>
    <table>
    <tr>
    <td>
        <asp:Label runat="server" Text="Name" ForeColor="White"></asp:Label>
    </td>
     <td>
         <asp:TextBox ID="txtVendorName" runat="server"></asp:TextBox>
        </td>
    </tr>
    <tr>
    <td>
        <asp:Label ID="Label1" runat="server" Text="ProductName" ForeColor="White"></asp:Label>
    </td>
    <td>
        <asp:TextBox ID="txtProductName" runat="server"></asp:TextBox>
    </td>
    </tr>
    <tr>
    <td>
        <asp:Label ID="Label3" runat="server" Text="Category" ForeColor="White"></asp:Label>
    </td>
    <td>
        <asp:DropDownList ID="txtCategory" runat="server">
            <asp:ListItem>Computer</asp:ListItem>
            <asp:ListItem>Airconditioner</asp:ListItem>
            <asp:ListItem>HomeAppliances</asp:ListItem>
        </asp:DropDownList>
    </td>
    </tr>
    <tr>
    <td>
        <asp:Label ID="Label2" runat="server" Text="Price" ForeColor="White"></asp:Label>
    </td>
    <td>
        <asp:TextBox ID="txtPrice" runat="server"></asp:TextBox>
    </td>
    </tr>

    <tr>
            <td class="style1" style="color: #FFFFFF">Browse product IMAGE </td>
            <td>
                <asp:FileUpload ID="FileUpload1"  runat="server" />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                    ControlToValidate="FileUpload1" ErrorMessage="show image path"></asp:RequiredFieldValidator>
            </td>
        </tr>
   
    <tr>
    <td>
        <asp:Button ID="btnAdd" runat="server" Text="ADD" Width="124px" 
            onclick="btnAdd_Click" />
    </td>
    <td>
        &nbsp;</td>
    </tr>
    </table>
</asp:Content>

